server:
  port: 11001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: cloud-user
  profiles:
    active: peer1
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#      config:
#        server-addr: 127.0.0.1:8848
#        name: localhost

---
spring:
  profiles: peer1


---
spring:
  profiles: peer2
